name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'  # Weekly run on Mondays

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing code changes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Debug Environment Variables
        run: |
          echo "Checking if secrets are available..."
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Checking Docker Status..."
          docker version
      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/application-game:${{ github.run_id }}
          platforms: linux/amd64,linux/arm64

  trivy-security-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Syft
        run: |
          curl -sSL https://github.com/anchore/syft/releases/download/v0.56.0/syft_0.56.0_linux_amd64.tar.gz | tar xz -C /usr/local/bin syft
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
      - name: Generate SBOM using Syft
        run: |
          syft . -o cyclonedx-xml > sbom.xml  # Use CycloneDX XML format
      - name: Run Trivy FS Scan (Source Code Vulnerabilities)
        run: |
          trivy fs --exit-code 1 --severity HIGH,CRITICAL --format table . > trivy-fs-results.txt
      - name: Run Trivy Image Scan (Container Image Vulnerabilities)
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL --format table -o trivy-image-results.txt ${{ secrets.DOCKERHUB_USERNAME }}/application-game:${{ github.run_id }} || true
      - name: Upload Trivy FS Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-results
          path: trivy-fs-results.txt
      - name: Upload Trivy Image Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-results
          path: trivy-image-results.txt
      - name: Upload Trivy SBOM Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-results
          path: sbom.xml

  update-helm-chart:
    name: Update Helm Chart
    runs-on: ubuntu-latest
    needs: trivy-security-scan
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.email "omraut0508@gmail.com"
          git config --global user.name "om0508"
      - name: Stash changes if any
        run: |
          git diff --quiet || git stash -u  # Stash changes if there are unstaged changes
      - name: Pull latest changes from remote
        run: |
          git pull origin main --rebase  # Pull latest changes and rebase
      - name: Update Helm Chart Tag
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' application-game-charts/values.yaml
      - name: Commit and Push Changes
        run: |
          git add application-game-charts/values.yaml
          git commit -m "Update tag in Helm chart"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/om0508/Automated-CI-CD.git
          git push origin main
